name: RepoAuditor

on: 
  workflow_dispatch:

jobs:
  audit-repo:
    runs-on: ubuntu-latest
    steps:
      - uses: mtanneau/repoauditor-action@v0.1.0
        with:
          github_pat: ${{ secrets.REPO_AUDITOR_PAT }}
